# Generated by Django 5.2.14 on 2026-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='exam_time',
            field=models.CharField(max_length=50),
        ),
    ]
