# Generated by Django 5.2.14 on 2026-05-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_timetable_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='college_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
